### ISSUE TITLE
Failed to npm install node helloworld

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-common#221]
I got this error when I do `npm install`

```
stanleycheung@gummybear:~/grpc-common/node$ npm install
npm WARN package.json grpc-demo@0.5.0 No repository field.
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/grpc
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/grpc
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/protobufjs
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/protobufjs
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/bytebuffer
npm http GET https://registry.npmjs.org/ascli
npm http 304 https://registry.npmjs.org/ascli
npm http 304 https://registry.npmjs.org/bytebuffer
npm http GET https://registry.npmjs.org/colour
npm http GET https://registry.npmjs.org/optjs
npm http GET https://registry.npmjs.org/long
npm http GET https://registry.npmjs.org/bufferview
npm http 304 https://registry.npmjs.org/long
npm http 304 https://registry.npmjs.org/colour
npm http 304 https://registry.npmjs.org/optjs
npm http 304 https://registry.npmjs.org/bufferview

> grpc@0.5.5 install /usr/local/google/home/stanleycheung/grpc-common/node/node_modules/grpc
> node-gyp rebuild

make: Entering directory `/usr/local/google/home/stanleycheung/grpc-common/node/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc/ext/call.o
  CXX(target) Release/obj.target/grpc/ext/channel.o
  CXX(target) Release/obj.target/grpc/ext/completion_queue_async_worker.o
../ext/completion_queue_async_worker.cc: In member function ‘virtual void grpc::node::CompletionQueueAsyncWorker::Execute()’:
../ext/completion_queue_async_worker.cc:60:10: error: cannot convert ‘grpc_event’ to ‘grpc_event*’ in assignment
   result = grpc_completion_queue_next(queue, gpr_inf_future);
          ^
../ext/completion_queue_async_worker.cc:61:15: error: ‘grpc_event’ has no member named ‘data’
   if (result->data.op_complete != GRPC_OP_OK) {
               ^
../ext/completion_queue_async_worker.cc:61:35: error: ‘GRPC_OP_OK’ was not declared in this scope
   if (result->data.op_complete != GRPC_OP_OK) {
                                   ^
../ext/completion_queue_async_worker.cc: In member function ‘virtual void grpc::node::CompletionQueueAsyncWorker::HandleOKCallback()’:
../ext/completion_queue_async_worker.cc:86:27: error: ‘grpc_event_finish’ was not declared in this scope
   grpc_event_finish(result);
                           ^
../ext/completion_queue_async_worker.cc: In member function ‘virtual void grpc::node::CompletionQueueAsyncWorker::HandleErrorCallback()’:
../ext/completion_queue_async_worker.cc:98:27: error: ‘grpc_event_finish’ was not declared in this scope
   grpc_event_finish(result);
                           ^
make: *** [Release/obj.target/grpc/ext/completion_queue_async_worker.o] Error 1
make: Leaving directory `/usr/local/google/home/stanleycheung/grpc-common/node/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-52-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/google/home/stanleycheung/grpc-common/node/node_modules/grpc
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0
stanleycheung@gummybear:~/grpc-common/node$ 
```

I have `nodejs-legacy` installed. `npm install` works under `grpc/src/node`. I have tried to delete the entire `node_modules` folder and start over. I have tried to re-compile the grpc C core. Any idea?

**Comment by stanley-cheung** [comment]
It's some version mismatch. Will submit a PR for this
