### ISSUE TITLE
grpc: c++ server and java client  

### ISSUE THREAD

**Issue by garygogo** [grpc/grpc-common#281]
I used "grpc-java/examlpe/route-guide-client" as a client and "grpc-common/cpp/route_guide_server" as a server.I got the error message:

com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED
	at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
	at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
	at io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:204)
	at io.grpc.examples.routeguide.RouteGuideClient.getFeature(RouteGuideClient.java:81)
	at io.grpc.examples.routeguide.RouteGuideClient.main(RouteGuideClient.java:233)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
	at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:402)
	at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED
	at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
	at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
	at io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub.getFeature(RouteGuideGrpc.java:204)
	at io.grpc.examples.routeguide.RouteGuideClient.getFeature(RouteGuideClient.java:81)
	at io.grpc.examples.routeguide.RouteGuideClient.main(RouteGuideClient.java:233)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
	at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:402)
	at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
It can't do like this between java and c++,or how can I fix it?
thanks.

**Comment by louiscryan** [comment]
Fixed by

https://github.com/grpc/grpc/commit/9a72021cc6c32837869be7fab406ec620d91f595
